# Generated by Django 4.1.7 on 2023-05-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_candidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
